[tool.poetry]
name = "project1-energy-analysis"
version = "0.1.0"
description = "Energy analysis dashboard"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "*"
requests = "*"
python-dotenv = "*"
pyyaml = "*"
streamlit = "*"
plotly = "*"
statsmodels = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"







