[tool.poetry]
name = "project1-energy-analysis"
version = "0.1.0"
description = "US Weather + Energy Analysis Pipeline"
authors = ["Francis Happy <your.email@example.com>"]
package-mode = false

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
